ARG UBUNTU_VERSION

FROM nvidia/cuda:12.1.0-base-ubuntu22.04

WORKDIR /app

ENV DEBIAN_FRONTEND=noninteractive

RUN sed -i 's/archive.ubuntu.com/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list
RUN apt update
RUN apt install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" keyboard-configuration
RUN apt install -y git
RUN apt install -y ffmpeg
RUN apt install -y software-properties-common
RUN apt install -y python3-pip

RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117
RUN pip install git+https://github.com/openai/whisper.git

RUN pip install pysubs2
