version: '3'

services:
  whisper:
    container_name: whisper-dev
    volumes:
      - ../.devcontainer:/app/.devcontainer
      - ../docker:/app/docker
      - ../src:/app/src
      - ../models:/app/models
      - ../.env:/app/.env
    command: sleep infinity
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
