version: '3'

services:
  whisper:
    container_name: whisper-dev
    volumes:
      - ../.devcontainer:/app/.devcontainer
      - ../docker:/app/docker
      - ../src:/app/src
    command: sleep infinity
